### ISSUE TITLE
Reference to alternative project turbolift

### ISSUE THREAD

**Issue by nitrocode** [Clever/microplane#100]
Some projects have an alternative projects section.

What do you folks think of linking to newcomer [turbolift](https://github.com/Skyscanner/turbolift)?

Even better would be to document the differences or pros and cons between the two.

**Comment by nathanleiby** [comment]
@nitrocode thanks for the recommendation! As a quick fix, I've added a link to turbolift as a related project. 

https://github.com/Clever/microplane/pull/104

If you had time, I'd be grateful if shared any thoughts on the differences or pros/cons. I haven't yet had a chance to use it beyond reading their README.

**Comment by cobraz** [comment]
[Octoherd](https://github.com/octoherd/cli) is an alternative to microplane. They're hooked into the Github API for the most part; not really using Git in any way. Which means it's limited to using Github API to do automated changes (you'll have to open potential pull-requests on your own). Regardless, it is an alternative to `microplane´, right? :)

**Comment by nathanleiby** [comment]
Added Octoherd as a related project https://github.com/Clever/microplane/commit/8024b4501c9678fd76bf9b41cde7b61c0f9ce976

**Comment by taylor-sutton** [comment]
One thing that seems promising about turbolift's model is that it doesn't try to manage the lifecycle of running the actual change as heavily. Doing large-scale changes with microplane, I often find cases where I need to hand-hold some of the target repos or add on additional commits to them, etc. Our model of "one script that runs once starting from the cloned repo and produces the final thing in one go" with `mp plan` is less convenient for that (For example, `mp plan` always runs against `cloned/` , there's no way to run a second script against repos after the first one finishes)
