### ISSUE TITLE
MP Clone Exit Code 128

### ISSUE THREAD

**Issue by Cerelius** [Clever/microplane#101]
When trying to push to a list of repositories sometimes it will fail with exit code 128. I believe this error is caused by insufficient access permissions while trying to clone. I understand why this is thrown and it can be resolved by updating the permissions but it would be nice if the failures would include which repo is throwing the error so the entire list doesn't have to be checked for permissions. 

The snippet below shows output where part of a list has failed with exit code 128 but I have no idea which one is the problem. With a list of 10 repos this isn't a huge problem but when pushing to 200 repos it takes a very long time to check the permissions in each one. 

*Repo names removed as an abundance of caution*

```
/home/runner/work/REMOVED
2021/08/02 20:25:21 cloning: REMOVED
2021/08/02 20:25:21 cloning: REMOVED
2021/08/02 20:25:21 cloning: REMOVED
2021/08/02 20:25:21 cloning: REMOVED
2021/08/02 20:25:21 cloning: REMOVED
2021/08/02 20:25:21 cloning: REMOVED
2021/08/02 20:25:21 cloning: REMOVED
2021/08/02 20:25:21 cloning: REMOVED
2021/08/02 20:25:21 cloning: REMOVED
2021/08/02 20:25:21 cloning: REMOVED
2021/08/02 20:25:22 multiple errors: exit status 128 | exit status 128 | exit status 128 | exit status 128
Error: Process completed with exit code 1.
```

**Comment by taylor-sutton** [comment]
Hello,

In this case, can you use `mp status` to check which repositories had failed, as a workaround? `status` ought to show individual status for each target repository. I find myself piping the result of `mp status` into a quick grep to find repos with issues.

That said, we could probably still improve the error message here.

**Comment by t-h-o** [comment]
That definitely works for this use case; however, it may be worth the effort to include a `--verbose` command of sorts? We may look into this 👍🏻

**Comment by Cerelius** [comment]
We were able to make the status command work for us using the mp `mp status` command. A `--verbose` logging flag would be helpful. I also wanted to ask if `mp status` is included in the documentation anywhere because I didn't realize that it existed until your comment. 

We were able to make this work so I can close the issue. Thank you!
