### ISSUE TITLE
Create a topic for microplane

### ISSUE THREAD

**Issue by cobraz** [Clever/microplane#106]
I've got a few repositories I'm thinking about making public. These are typical workloads that I use `microplane` with. Stuff like normalizing `package.json` in Typescript/JS repositories. I noticed recently [Octoherd](https://github.com/octoherd) (which also is a potential project to link to, re #104), their asking contributors to tag their repositories with `octoherd` which they link to.

See: https://github.com/topics/octoherd-script

Maybe we can use |#microplane](https://github.com/topics/microplane) or [#microplane-script](https://github.com/topics/microplane-script). I can coordinate adding a few projects to these topics and open a pull request to add the topic reference to the README.

What do you think?

**Comment by nathanleiby** [comment]
Adding `#microplane` as the topic sounds good! We can add it to this repo too.

@taylor-sutton or @rgarcia I'm not able to edit the topics on the repo - would you mind adding it or granting me access to do so? Thanks!

https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/classifying-your-repository-with-topics

**Comment by taylor-sutton** [comment]
> Adding `#microplane` as the topic sounds good! We can add it to this repo too.
> 
> @taylor-sutton or @rgarcia I'm not able to edit the topics on the repo - would you mind adding it or granting me access to do so? Thanks!
> 
> https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/classifying-your-repository-with-topics

I've added you with `Maintain` permissions - can you check if that allows you to manage topics?

**Comment by nathanleiby** [comment]
@taylor-sutton that worked.  I've added `#microplane` as a tag to this repo. Thanks!

**Comment by nathanleiby** [comment]
> Maybe we can use |#microplane](https://github.com/topics/microplane) or #microplane-script. I can coordinate adding a few projects to these topics and open a pull request to add the topic reference to the README.
> 
> What do you think?

@cobraz We should now be all set to link other repos via this topic. Thanks again for the suggestion.
