### ISSUE TITLE
Unclear documentation on how to use multiple labels with push command

### ISSUE THREAD

**Issue by laynegeck** [Clever/microplane#129]
It would be very helpful to add an example to the `mp push` documentation on how to add multiple labels 🙏

**Comment by nathanleiby** [comment]
Hi @laynegeck - thanks for the suggestion! Can do. 

Labels are parsed using `GetStringSlice`
https://github.com/Clever/microplane/blob/52adc7f1dad089104951619e505ec008f2d90512/cmd/push.go#L72

I believe they are white-space delimited https://github.com/spf13/viper/issues/830#issue-551132549 … So I expect something like:
```
mp push --labels 'foo bar baz' … 
```
should do the trick!

Is that your experience? I can test or dig into the code further to be certain.

**Comment by laynegeck** [comment]
After trial and error, I found out that the above code would add a single label with spaces in it
To add multiple labels, you have to do something like the following:
```mp push -l 'a single label with spaces in it' -l a_second_label_without_spaces```

**Comment by nathanleiby** [comment]
I've opened PR #137 to resolve this. Please lmk if this meets your expectations for clearer docs. Thanks again for the suggestion!
